spring:
  application:
    name: zone-service
  cloud:
    config:
      enabled: true
  config:
    import: "configserver:http://localhost:8888"

iot:
  provider:
    url: http://localhost:9090/api
    username: sachintha_p
    password: 12345678